var fulltext = [
    "<script src=\"js/vendor/decimal/5.0.8/decimal.min.js?ver=5.0.8\"><\/script>",
    "<script src=\"js/vendor/angular/1.5.5/angular.min.js?ver=1.5.5\"><\/script>",
    "<script src=\"js/vendor/angular/1.5.5/angular-sanitize.min.js?ver=1.5.5\"><\/script>",
    "<script src=\"js/vendor/angular/1.5.5/angular-route.min.js?ver=1.5.5\"><\/script>",
    "<script src=\"js/vendor/angular/1.5.5/angular-touch.min.js?ver=1.5.5\"><\/script>",
    "<script src=\"js/vendor/ui-bootstrap/1.3.2/ui-bootstrap-tpls.min.js?ver=1.3.2\"><\/script>",
    "<script src=\"js/vendor/moment/2.12.0/moment.min.js?ver=2.12.0\"><\/script>",
    "<script src=\"js/vendor/angular-translate/2.11.0/angular-translate.min.js?ver=2.11.0\"><\/script>",
    "<script src=\"js/vendor/angular-validation/1.5.1/angular-validation.min.js?ver=1.5.1\"><\/script>",
    "<script src=\"js/vendor/ng-window-manager/wmwindow.js?ver=master\"><\/script>",
    "<script src=\"js/vendor/sockjs/1.1.0/sockjs.min.js?ver=1.1.0\"><\/script>",
    "<script src=\"js/vendor/stomp/stomp.js?ver=2.3.4\"><\/script>",
    "<script src=\"js/vendor/prototype/string.js?ver=master\"><\/script>",
    "<script src=\"js/vendor/prototype/datetime.js?ver=master\"><\/script>",
    "<script src=\"js/vendor/idle/1.0.0/idle.min.js?ver=1.0.0\"><\/script>",
    "<script src=\"js/vendor/loading-bar/0.9.0/loading-bar.min.js?ver=0.8.0\"><\/script>",
    "<script src=\"js/vendor/xlsx-reader/0.8.0/jszip.js?ver=0.8.0\"><\/script>",
    "<script src=\"js/vendor/xlsx-reader/0.8.0/xlsx.min.js?ver=0.8.0\"><\/script>",
    "<script src=\"js/vendor/xlsx-reader/0.8.0/ods.js?ver=0.8.0.001\"><\/script>",
    "<script src=\"js/vendor/file-saver/FileSaver.min.js?ver=master\"><\/script>",
    "<script src=\"js/vendor/ag-grid/4.0.7/ag-grid-enterprise.js?ver=4.0.7\"><\/script>",
    "<script src=\"js/vendor/lokijs/1.3.16/lokijs.min.js?ver=1.3.16\"><\/script>",
    "<script src=\"js/vendor/lokijs/1.3.16/loki-angular.js?ver=1.3.16\"><\/script>",
    "<script src=\"js/vendor/desktop-notify/desktop-notify.js?ver=master\"><\/script>",
    "<script src=\"js/vendor/angular-toastr/1.7.0/angular-toastr.tpls.js?ver=1.7.0\"><\/script>",
    "<script src=\"js/vendor/datePicker/6.3.6/lang/en.js?ver=6.3.6.001\"><\/script>",
    "<script src=\"js/vendor/datePicker/6.3.6/datepicker.js?ver=6.3.6.007\"><\/script>",
    "<script src=\"js/vendor/timePicker/ngTimepicker.js?ver=1.0.0.001\"><\/script>",
    "<script src=\"js/vendor/highcharts/4.2.4/highcharts.js?ver=4.2.4\"><\/script>",
    "<script src=\"js/vendor/highcharts/4.2.4/modules/exporting.js?ver=4.2.4\"><\/script>",
    "<script src=\"js/vendor/highcharts/4.2.4/modules/offline-exporting.js?ver=4.2.4\"><\/script>"
];

document.write(fulltext.join(''));